/**
 * Turns a binary STL into the compact mesh the putter scene draws.
 *
 *   node scripts/prep-mesh.mjs
 *
 * The STL that comes out of Fusion is 427 KB of 32-bit floats, and every byte
 * of it would be base64-inlined into the single-file build at a 33% premium.
 * Almost all of that is precision the piece will never show at 400px on a
 * screen, so this:
 *
 *   1. reads the triangles,
 *   2. centres the model on its own bounding box and scales it to fit a unit
 *      cube, so the scene never has to know the part's real dimensions,
 *   3. quantises each coordinate to a 16-bit integer, which is finer than one
 *      screen pixel at any size this is drawn,
 *   4. writes the result as base64 in a .ts module, so the bundler treats it as
 *      code and inlines it with no loader and no fetch.
 *
 * Normals are recomputed in the scene from the vertices rather than stored:
 * they are a third of the file and derivable exactly.
 */
import { readFile, writeFile } from "node:fs/promises";

const SRC = "assets-src/putter/putter-v3.stl";
const OUT = "src/scenes/putter/mesh.ts";

const buf = await readFile(SRC);
if (buf.subarray(0, 5).toString() === "solid" && buf.length < 84) {
  throw new Error("ASCII STL: this script only reads binary STL");
}

const count = buf.readUInt32LE(80);
console.log(`${count} triangles`);

// Each record: 12 floats (normal + 3 vertices) then a 2-byte attribute count.
const RECORD = 50;
const verts = new Float32Array(count * 9);
let v = 0;
for (let i = 0; i < count; i++) {
  const at = 84 + i * RECORD + 12; // skip the stored normal
  for (let j = 0; j < 9; j++) verts[v++] = buf.readFloatLE(at + j * 4);
}

// Bounding box, so the scene can draw any part without knowing its size.
let minX = Infinity, minY = Infinity, minZ = Infinity;
let maxX = -Infinity, maxY = -Infinity, maxZ = -Infinity;
for (let i = 0; i < verts.length; i += 3) {
  const [x, y, z] = [verts[i], verts[i + 1], verts[i + 2]];
  if (x < minX) minX = x;
  if (y < minY) minY = y;
  if (z < minZ) minZ = z;
  if (x > maxX) maxX = x;
  if (y > maxY) maxY = y;
  if (z > maxZ) maxZ = z;
}
const cx = (minX + maxX) / 2, cy = (minY + maxY) / 2, cz = (minZ + maxZ) / 2;
const span = Math.max(maxX - minX, maxY - minY, maxZ - minZ);
console.log(
  `bounds ${(maxX - minX).toFixed(1)} x ${(maxY - minY).toFixed(1)} x ${(maxZ - minZ).toFixed(1)}`,
);

// Centre, normalise to [-0.5, 0.5], then quantise to uint16.
const q = new Uint16Array(verts.length);
for (let i = 0; i < verts.length; i += 3) {
  const nx = (verts[i] - cx) / span;
  const ny = (verts[i + 1] - cy) / span;
  const nz = (verts[i + 2] - cz) / span;
  q[i] = Math.round((nx + 0.5) * 65535);
  q[i + 1] = Math.round((ny + 0.5) * 65535);
  q[i + 2] = Math.round((nz + 0.5) * 65535);
}

const b64 = Buffer.from(q.buffer).toString("base64");

await writeFile(
  OUT,
  `/**
 * The putter head, generated by scripts/prep-mesh.mjs from
 * ${SRC}. Do not edit by hand.
 *
 * ${count} triangles, centred on the origin and scaled to fit a unit cube, with
 * every coordinate quantised to a uint16. Normals are derived in the scene.
 */
export const TRIANGLES = ${count};

const PACKED =
  "${b64}";

/** Decodes to a flat [x, y, z, ...] array in the range [-0.5, 0.5]. */
export function vertices(): Float32Array {
  const bin = atob(PACKED);
  const bytes = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
  const q = new Uint16Array(bytes.buffer);
  const out = new Float32Array(q.length);
  for (let i = 0; i < q.length; i++) out[i] = q[i] / 65535 - 0.5;
  return out;
}
`,
  "utf8",
);

console.log(`wrote ${OUT}  (${(b64.length / 1024).toFixed(1)} KB base64)`);
